[workspace]
resolver = "2"
members = ["lgn-auth", "lgn-messages", "lgn-provers", "lgn-worker"]

[workspace.dependencies]
mp2_common = { git = "http://github.com/Lagrange-Labs/mapreduce-plonky2.git", branch = "main" }
mp2_v1 = { git = "http://github.com/Lagrange-Labs/mapreduce-plonky2.git", branch = "main" }
parsil = { git = "http://github.com/Lagrange-Labs/mapreduce-plonky2.git", branch = "main" }
verifiable-db = { git = "https://github.com/Lagrange-Labs/mapreduce-plonky2.git", branch = "main" }

[patch.crates-io]
plonky2 = { git = "https://github.com/Lagrange-Labs/plonky2", branch = "upstream" }
plonky2_field = { git = "https://github.com/Lagrange-Labs/plonky2", branch = "upstream" }
